issue 77 - formatting issue when function is used with a reserved keyword in the function name eg function class()
rokucommunity/brighterscript-formatter pull request #96
Opened 2024-12-09 09:15 UTC by philanderson888

work in progress

initial commit

very messy code

appear to have generated a fix though

2024-12-09 10:43 UTC, philanderson888 commented
pipeline failing on 

<img width="648" alt="Screenshot 2024-12-09 at 10 41 46" src="https://github.com/user-attachments/assets/0ee1c0de-a6fd-43af-b2e9-0513375d4d7c">

not sure exactly what this means - if it is something to be concerned about or not.  looks like a library issue, we can look at this later after we agree the fix in principle.

2024-12-09 12:56 UTC, TwitchBronBron commented
> pipeline failing on
> 
> <img alt="Screenshot 2024-12-09 at 10 41 46" width="648" src="https://private-user-images.githubusercontent.com/8657188/393802727-0ee1c0de-a6fd-43af-b2e9-0513375d4d7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDkyNzcsIm5iZiI6MTczMzc0ODk3NywicGF0aCI6Ii84NjU3MTg4LzM5MzgwMjcyNy0wZWUxYzBkZS1hNmZkLTQzYWYtYjJlOS0wNTEzMzc1ZDRkN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMTI1NjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTI3NmVkOWUwMjNmNjYxZTRmYzM3MDI2M2IyMWIxYTA1OTY3ZTgxODcxOTJiZGE1MTIzYTJkOTRhZjkxMWMzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Qu03q0bb27xVLiY4w0BbNFkfxS-aa62qe1m1y_rl5xA">
> not sure exactly what this means - if it is something to be concerned about or not. looks like a library issue, we can look at this later after we agree the fix in principle.

This issue is caused by the local install of brighterscript. Revert this change and then run `npm install` again in the `brighterscript-formatter` project, then commit your package.json and package-lock.json and it should resolve.

![image](https://github.com/user-attachments/assets/9b12d78d-2b2b-42dc-beb7-796028e9136a)

2025-01-03 21:33 UTC, philanderson888 commented
just rolled back all the commits to remove the `package.json` and `package-lock.json` files from the commits, then re-committed all the other changes.

just waiting to see if all the Github build tests pass now ...

2025-01-03 21:42 UTC, philanderson888 commented
seems to be failing on code coverage not quite 100%

<img width="822" alt="Screenshot 2025-01-03 at 21 39 16" src="https://github.com/user-attachments/assets/5719ee94-81cf-4241-96f7-08b50eafc515" />

at least it's not an error introduced by the changes `per se`, it's a code coverage error which we can deal with later ... will investigate later.

will tidy up code changes first.

2025-01-05 22:26 UTC, philanderson888 commented
code is tidy now

test is failing above because ... looks like ... code coverage is not 100%, not because of an error in the changes

I will have to look into writing fresh tests to cover extra code, to bring test coverage back up to 100%

2025-01-10 09:31 UTC, philanderson888 commented
OK @TwitchBronBron looks like 

- code is working
- tests are passing

cc

@chrisdp @markwpearce @heart-of-code @addison-adler

2025-01-22 19:10 UTC, TwitchBronBron requested changes
@philanderson888 I pushed a test that's failing and needs to be fixed. Can you take a look?

2025-01-28 10:42 UTC, philanderson888 commented
Hey 

@chrisdp @markwpearce @heart-of-code @addison-adler

@TwitchBronBron added a Try ... Catch failing test as well into the mix, which I have fixed (I think!)

So code is ready for second round of code reviews, thanks all

![Screenshot 2025-01-28 at 10 39 55](https://github.com/user-attachments/assets/a59f1608-15db-4529-ac98-7cb978e06336)



here is output of bsfmt function after changes implemented

`
function doThis()
end function

function class()
end function

function try()
    print "hello"
end function

function enum()
end function

function interface()
    try
        print "hello"
    catch
    end try
end function

function try()
    print "hello"
    try
        print "hello"
    catch e
        print "hello"
    end try
end function
`

2025-01-29 15:15 UTC, TwitchBronBron approved these changes
I tested this on a large internal project, and everything worked as expected. I think this is good to go! Nice work.

2025-01-29 15:40 UTC, merged

2025-01-30 03:28 UTC, philanderson888 commented
Thanks @TwitchBronBron appreciate that

Happy to help

cc @addison-adler let me know if this helps you, now that it's merged!